server:
  port: 33332
# datasource
spring:
  datasource:
      url: jdbc:mysql://10.20.10.4:3306/lsmspbig?characterEncoding=utf8
      username: root
      password: YiNbAI_4I6QUan
      tomcat:
        initial-size: 2
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect